### ISSUE TITLE
Using backup gem with Openshift app

### ISSUE THREAD

**Issue by amnesia7** [backup/backup#647]
I'm giving this gem a go to backup the database for my Openshift app.

I've setup the default config  for mail in the `my_backup.rb` config file.

I've set the `models/my_backup.rb` file to be postgresql with the various environment variables that Openshift provides for the db name, user etc (I've left the socket as the example one because I wasn't sure what else to use).
I've set it to just do a local backup to the writeable `data` folder that Openshift makes available within the app area as well.
I've set it to compress with gzip and send an email for success/warning/error.

However, I get the following error output when I try to run `backup perform -t my_backup -c /var/lib/openshift/123456789/app-root/repo/Backup/models/my_backup.rb`:

```
[2015/04/06 21:17:04][error] CLI::Error
[2015/04/06 21:17:04][error] --- Wrapped Exception ---
[2015/04/06 21:17:04][error] Errno::EACCES: Permission denied - /var/lib/openshift/123456789/Backup
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:245:in `mkdir'
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:245:in `fu_mkdir'
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:219:in `block (2 levels) in mkdir_p'
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:217:in `reverse_each'
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:217:in `block in mkdir_p'
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:203:in `each'
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:203:in `mkdir_p'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/logger/logfile.rb:104:in `setup_logfile'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/logger/logfile.rb:82:in `initialize'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/logger.rb:169:in `new'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/logger.rb:169:in `block in start!'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/logger.rb:168:in `each'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/logger.rb:168:in `start!'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/cli.rb:141:in `perform'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/bin/backup:5:in `<top (required)>'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/bin/backup:23:in `load'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/bin/backup:23:in `<main>'
[2015/04/06 21:17:04][error] CLI::Error
[2015/04/06 21:17:04][error] --- Wrapped Exception ---
[2015/04/06 21:17:04][error] Errno::EACCES: Permission denied - /var/lib/openshift/123456789/Backup
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:245:in `mkdir'
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:245:in `fu_mkdir'
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:219:in `block (2 levels) in mkdir_p'
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:217:in `reverse_each'
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:217:in `block in mkdir_p'
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:203:in `each'
[2015/04/06 21:17:04][error] /opt/rh/ruby200/root/usr/share/ruby/fileutils.rb:203:in `mkdir_p'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/logger/logfile.rb:104:in `setup_logfile'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/logger/logfile.rb:82:in `initialize'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/logger.rb:169:in `new'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/logger.rb:169:in `block in start!'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/logger.rb:168:in `each'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/logger.rb:168:in `start!'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/lib/backup/cli.rb:141:in `perform'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/gems/backup-4.1.8/bin/backup:5:in `<top (required)>'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/bin/backup:23:in `load'
[2015/04/06 21:17:04][error] /var/lib/openshift/123456789/.gem/bin/backup:23:in `<main>'
```

It looks like it is denied permission to create a folder at the top level in my Openshift app area when really it should be working in the `data` folder that is for use.

I assume I need to set a folder location in the config for it to use rather than the default `Backup` folder so that I can use `data` folder that Openshift makes available for use but I could do with some guidance on each of the config bits that I would need to set.

It might just be the root folder location that I need to set but I just wanted to check if that's the case or not.

Thanks

**Comment by amnesia7** [comment]
Ok, it now works if I use the following in config:
```
root_path ENV['OPENSHIFT_DATA_DIR']
```
```
tmp_path ENV['OPENSHIFT_TMP_DIR']
```
```
data_path 'data'
```
and comment out the `db.socket` because I'm using a scaled app. I think there's an environment variable for socket if on a non-scaled app.

I've setup a gmail account to use to send the emails and it worked the first time but it has failed every time since with the following:
```
[2015/04/07 21:17:45][info] Notifier::Error: Retry #1 of 10.
[2015/04/07 21:17:45][info] --- Wrapped Exception ---
[2015/04/07 21:17:45][info] Net::SMTPAuthenticationError: 534-5.7.9 Please log in with your web browser and then try again. Learn more at
```
Here's my mail config:
```
  Notifier::Mail.defaults do |mail|
    mail.from                 = 'fromemailaddress@mydomain.com'
    mail.to                   = 'toemailaddress@mydomain.com'
    mail.address              = 'smtp.gmail.com'
    mail.port                 = 587
    mail.domain               = 'my-domain.rhcloud.com'
    mail.user_name            = 'mymailer@gmail.com'
    mail.password             = '[mymailerpassword]'
    mail.authentication       = 'plain'
    mail.encryption           = :starttls
  end
```
Any ideas why it would throw the error message after it had worked once?

If I try signing into the email account in my computer's web browser for the mailer Google says there's been strange activity on my account and I need to verify it using an SMS code. Is that the issue and if so is there a solution that I'm missing?

**Comment by amnesia7** [comment]
Nevermind, I've used my own domain for the mailer instead and that's working fine.
