### ISSUE TITLE
backup for ceph

### ISSUE THREAD

**Issue by mm12333** [backup/backup#690]
Hi,
I use http://ceph.com/ for storage backups, and as provider i use S3. 
But i get erorr for request:

```
 CloudIO::Error: Retry #1 of 1
[2015/08/19 11:26:01][info]   Operation: PUT 'backups/mongo/bkp/2015.08.19.11.25.45/bkp.tar'
[2015/08/19 11:26:01][info] --- Wrapped Exception ---
[2015/08/19 11:26:01][info] Excon::Errors::BadRequest: Expected(200) <=> Actual(400 Bad Request)
[2015/08/19 11:26:01][info] excon.error.response
[2015/08/19 11:26:01][info]   :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>InvalidArgument</Code></Error>"
[2015/08/19 11:26:01][info]   :headers       => {
[2015/08/19 11:26:01][info]     "Accept-Ranges"  => "bytes"
[2015/08/19 11:26:01][info]     "Connection"     => "close"
[2015/08/19 11:26:01][info]     "Content-Length" => "81"
[2015/08/19 11:26:01][info]     "Content-Type"   => "application/xml"
[2015/08/19 11:26:01][info]     "Date"           => "Wed, 19 Aug 2015 11:25:57 GMT"
[2015/08/19 11:26:01][info]     "Server"         => "Apache/2.2.22 (Debian)"
[2015/08/19 11:26:01][info]   }
[2015/08/19 11:26:01][info]   :local_address => "172...."
[2015/08/19 11:26:01][info]   :local_port    => 44063
[2015/08/19 11:26:01][info]   :reason_phrase => "Bad Request"
[2015/08/19 11:26:01][info]   :remote_ip     => "10....."
[2015/08/19 11:26:01][info]   :status        => 400

Backtrace:
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.44.4/lib/excon/middlewares/expects.rb:9:in `response_call'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.44.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.44.4/lib/excon/connection.rb:372:in `response'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.44.4/lib/excon/connection.rb:236:in `request'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fog-core-1.29.0/lib/fog/core/connection.rb:81:in `request'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fog-xml-0.1.1/lib/fog/xml/connection.rb:9:in `request'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fog-aws-0.1.1/lib/fog/aws/storage.rb:587:in `_request'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fog-aws-0.1.1/lib/fog/aws/storage.rb:582:in `request'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fog-aws-0.1.1/lib/fog/aws/requests/storage/put_object.rb:43:in `put_object'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/cloud_io/s3.rb:147:in `block (2 levels) in put_object'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/cloud_io/s3.rb:146:in `open'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/cloud_io/s3.rb:146:in `block in put_object'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/cloud_io/base.rb:21:in `with_retries'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/cloud_io/s3.rb:145:in `put_object'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/cloud_io/s3.rb:59:in `upload'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/storage/s3.rb:108:in `block in transfer!'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/storage/s3.rb:104:in `each'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/storage/s3.rb:104:in `transfer!'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/storage/base.rb:35:in `perform!'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/model.rb:334:in `block in store!'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/model.rb:332:in `map'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/model.rb:332:in `store!'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/model.rb:306:in `block in procedures'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/model.rb:269:in `call'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/model.rb:269:in `block in perform!'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/model.rb:268:in `each'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/model.rb:268:in `perform!'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/lib/backup/cli.rb:156:in `perform'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backup-4.1.11/bin/backup:5:in `<top (required)>'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/bin/backup:23:in `load'
[2015/08/19 11:26:33][error]   /home/mike/.rbenv/versions/2.2.2/bin/backup:23:in `<main>'
```

Request/response dump:

```
{:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.28.0 fog-core/1.29.0", "Content-Type"=>"application/x-tar", "Content-MD5"=>"...WYBDsiwwg==", "Host"=>"my.server.com", "x-amz-date"=>"20150819...", "x-amz-content-sha256"=>"STREAMING-AWS4-HMAC-SHA256-PAYLOAD", "x-amz-decoded-content-length"=>972800, "Content-Encoding"=>"aws-chunked", "Authorization"=>"AWS4-HMAC-SHA256 Credential=....., SignedHeaders=content-encoding;content-md5;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature="...fef575e0477f896....", "Transfer-Encoding"=>"chunked"}, :idempotent=>true, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>false, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.44.4 (x86_64-linux) ruby/2.2.2", :write_timeout=>60, :host=>"my.server.com", :hostname=>"my.server.com", :path=>"/backups/mongo/bkp/2015.08.19.11.25.45/bkp.tar", :port=>80, :query=>nil, :scheme=>"http", :expects=>200, :method=>"PUT", :request_block=>#<Fog::Storage::AWS::Real::S3Streamer:0x00562f801e2f98 @body=#<File:/home/mike/Backup/.tmp/bkp.tar>, @date=2015-08-19 11:26:26 UTC, @signature="...9784c9bba6d", @initial_signature="...9fef....", @signer=#<Fog::AWS::SignatureV4:0x00562f80bad910 @region="us-east-1", @service="s3", @aws_access_key_id="...KF", @hmac=#<Fog::HMAC:0x00562f80bad6e0 @key="AWS....", @digest=#<OpenSSL::Digest: e3b0c44298fc1c149afbf>, @signer=#<Proc:0x00562f80bad460@/home/mike/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fog-core-1.29.0/lib/fog/core/hmac.rb:28 (lambda)>>>, @finished=true>, :retries_remaining=>4, :connection=>#<Excon::Connection:562f801e1cb0 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.28.0 fog-core/1.29.0"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>false, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.44.4 (x86_64-linux) ruby/2.2.2", :write_timeout=>60, :host=>"my.server.com", :hostname=>"my.server.com", :path=>"", :port=>80, :query=>nil, :scheme=>"http"} @socket_key="http://my.server.com:80">, :stack=>#<Excon::Middleware::ResponseParser:0x00562f801de240 @stack=#<Excon::Middleware::Expects:0x00562f801de308 @stack=#<Excon::Middleware::Instrumentor:0x00562f801de3d0 @stack=#<Excon::Middleware::Mock:0x00562f801de6c8 @stack=#<Excon::Connection:562f801e1cb0 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.28.0 fog-core/1.29.0"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>false, :omit_default_port=>false, :persistent=>false, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.44.4 (x86_64-linux) ruby/2.2.2", :write_timeout=>60, :host=>"my.server.com", :hostname=>"my.server.com", :path=>"", :port=>80, :query=>nil, :scheme=>"http"} @socket_key="http://my.server.com:80">>>>>, :response=>{:body=>"<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>InvalidArgument</Code></Error>", :headers=>{"Date"=>"Wed, 19 Aug 2015 11:26:27 GMT", "Server"=>"Apache/2.2.22 (Debian)", "Accept-Ranges"=>"bytes", "Content-Length"=>"81", "Connection"=>"close", "Content-Type"=>"application/xml"}, :status=>400, :reason_phrase=>"Bad Request", :remote_ip=>"10....", :local_port=>44090, :local_address=>"172....."}}

```

Is it possible because i use not ceph provider ?

**Comment by tombruijn** [comment]
I'm not familiar with ceph. If you're just trying to connect to s3 you should be able to do that with the s3 authentication details. Where does ceph come in? And why not call s3 directly? So far as I know the s3 storage module was not specially tested on ceph.

**Comment by tombruijn** [comment]
Any update on this @mm12333 ?

**Comment by ramonskie** [comment]
you need the following
```
s3.fog_options = {:host=>"s3.yourdomain.com", :scheme=>"http", :port=>80, :aws_signature_version=>2
```

**Comment by mm12333** [comment]
thanks

**Comment by saminou** [comment]
@ramonskie why do we have to use Apache instead of civetweb?

**Comment by ramonskie** [comment]
@saminou there was a bug last year. but its probably solved by now

**Comment by saminou** [comment]
I'm curious @ramonskie was it this one?
https://github.com/civetweb/civetweb/issues/197
https://github.com/tus/tusd/pull/94

**Comment by ramonskie** [comment]
sorry im not sure. it was such a long time ago.
