### ISSUE TITLE
backup with mongodump gets stuck

### ISSUE THREAD

**Issue by sradu** [backup/backup#699]
First I want to say that I'm a huge fan of backup and you've done an amazing job.

We migrated our db to a new AWS instance and for some reason backup gets stuck at the end of the mongodump process. Running mongodump manually, the exact same command backup executes, ends correctly. Using mongo 3.0.6.

This is after I killed it after 6 hours. It usually takes 15 minutes. 

[2015/09/16 17:54:01][error]   2015-09-16T11:06:15.830+0000	[####################....]  production.tests   116941/135916  (86.0%)
[2015/09/16 17:54:01][error]   Killed
[2015/09/16 17:54:01][error] 
[2015/09/16 17:54:01][error] Backtrace:
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/backup-4.1.12/lib/backup/utilities.rb:199:in `run'
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/backup-4.1.12/lib/backup/utilities.rb:217:in `block (2 levels) in <module:Helpers>'
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/backup-4.1.12/lib/backup/database/mongodb.rb:78:in `dump!'
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/backup-4.1.12/lib/backup/database/mongodb.rb:61:in `perform!'
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/backup-4.1.12/lib/backup/model.rb:269:in `each'
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/backup-4.1.12/lib/backup/model.rb:269:in `block in perform!'
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/backup-4.1.12/lib/backup/model.rb:268:in `each'
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/backup-4.1.12/lib/backup/model.rb:268:in `perform!'
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/backup-4.1.12/lib/backup/cli.rb:156:in `perform'
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2015/09/16 17:54:01][error]   /var/lib/gems/2.1.0/gems/backup-4.1.12/bin/backup:5:in `<top (required)>'
[2015/09/16 17:54:01][error]   /usr/local/bin/backup:23:in `load'

this is ps aux before the kill -9. 
admin    2700  0.0  0.0  4328  752 ?        Ss  11:00  0:00 /bin/sh -c /usr/local/bin/backup perform --trigger standard
admin    2701  0.0  0.2 129936 48664 ?        Sl  11:00  0:01 /usr/bin/ruby2.1 /usr/local/bin/backup perform --trigger standard
admin    2707  0.0  0.0  4328  752 ?        S    11:00  0:00 sh -c /usr/bin/mongodump --db='production' --username='user'....
admin    2710  1.5  0.0 831792 12456 ?        Sl  11:00  6:27 /usr/bin/mongodump --db=production --username=user...

Not sure what other information to provide, it's definitely weird.

**Comment by tombruijn** [comment]
Hi @sradu sounds like a problem yes. 

Does the mongodump process still show up in the process list or has it exited already while backup is still running?

It sounds a bit like another problem that was reported. https://github.com/backup/backup/issues/617
If this problem is caused by the same problem I'm afraid we won't be able to fix it. The problem lay is in open4 that if there was too much output in a command it would hang. Try configuring mongodb that it doesn't provide any output in STDOUT.
Eventually the reporter worked around it by executing a command in a before block.

**Comment by sradu** [comment]
@tombruijn that's a great idea. Is there a simple way to add --quiet to the mongodump command via Backup?

**Comment by sradu** [comment]
--additional_options?

**Comment by tombruijn** [comment]
@sradu that would be the place to put it

 `mongodb.additional_options = ["--quiet"]`

**Comment by sradu** [comment]
--quiet did the trick, thanks @tombruijn!

**Comment by tombruijn** [comment]
Good to hear it's working @sradu !

**Comment by beeva-robertoandradas** [comment]
good trick, it works for me too.
