### ISSUE TITLE
FTP closes connection and Local storage

### ISSUE THREAD

**Issue by noff** [backup/backup#705]
Hello. Today received this log

```
[2015/10/03 21:30:06][info] Performing Backup for 'R46 shard 00 (shard00)'!
[2015/10/03 21:30:06][info] [ backup 4.2.0 : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux] ]
[2015/10/03 21:30:06][info] Database::PostgreSQL Started...
[2015/10/03 21:30:06][info] Using Compressor::Gzip for compression.
[2015/10/03 21:30:06][info]   Command: '/bin/gzip'
[2015/10/03 21:30:06][info]   Ext: '.gz'
[2015/10/03 22:08:00][info] Database::PostgreSQL Finished!
[2015/10/03 22:08:00][info] Packaging the backup files...
[2015/10/03 22:08:00][info] Running system utility 'tar'...
[2015/10/03 22:08:00][info] tar:STDOUT: tar (GNU tar) 1.26
[2015/10/03 22:08:00][info] tar:STDOUT: Copyright (C) 2011 Free Software Foundation, Inc.
[2015/10/03 22:08:00][info] tar:STDOUT: License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
[2015/10/03 22:08:00][info] tar:STDOUT: This is free software: you are free to change and redistribute it.
[2015/10/03 22:08:00][info] tar:STDOUT: There is NO WARRANTY, to the extent permitted by law.
[2015/10/03 22:08:00][info] tar:STDOUT: 
[2015/10/03 22:08:00][info] tar:STDOUT: Written by John Gilmore and Jay Fenlason.
[2015/10/03 22:10:16][info] Packaging Complete!
[2015/10/03 22:10:16][info] Cleaning up the temporary files...
[2015/10/03 22:10:17][info] Storage::FTP Started...
[2015/10/03 22:10:58][info] Storing 'ftp.selcdn.ru:backup/r46_a00/shard00/2015.10.03.21.30.06/shard00.tar'...
[2015/10/03 23:25:51][info] Storage::SFTP Started...
[2015/10/03 23:25:52][info] Storing 'hackday.ru:backup/r46_a00/shard00/2015.10.03.21.30.06/shard00.tar'...
[2015/10/04 00:23:23][info] Cycling Started...
[2015/10/04 00:23:23][info] Storage::SFTP Finished!
[2015/10/04 00:23:23][info] Storage::Local Started...
[2015/10/04 00:23:23][info] Storing '/home/rails/backups/r46_a00/shard00/2015.10.03.21.30.06/shard00.tar'...
[2015/10/04 00:23:23][info] Cycling Started...
[2015/10/04 00:23:23][info] Removing backup package dated 2015.09.28.21.30.14...
[2015/10/04 00:23:23][info] Storage::Local Finished!
[2015/10/04 00:23:23][error] Model::Error: Backup for R46 shard 00 (shard00) Failed!
[2015/10/04 00:23:23][error] --- Wrapped Exception ---
[2015/10/04 00:23:23][error] Net::FTPTempError: 426 Transfer aborted.  Data connection closed.
[2015/10/04 00:23:23][error] 
[2015/10/04 00:23:23][error] Backtrace:
[2015/10/04 00:23:23][error]   /home/rails/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/ftp.rb:325:in `getresp'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/ftp.rb:558:in `rescue in storbinary'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/ftp.rb:537:in `storbinary'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/ftp.rb:689:in `putbinaryfile'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/ftp.rb:717:in `put'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/storage/ftp.rb:58:in `block (2 levels) in transfer!'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/storage/ftp.rb:54:in `each'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/storage/ftp.rb:54:in `block in transfer!'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/storage/ftp.rb:46:in `block in connection'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/ftp.rb:135:in `open'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/storage/ftp.rb:44:in `connection'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/storage/ftp.rb:51:in `transfer!'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/storage/base.rb:45:in `perform!'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/model.rb:334:in `block in store!'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/model.rb:332:in `map'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/model.rb:332:in `store!'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/model.rb:306:in `block in procedures'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/model.rb:269:in `call'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/model.rb:269:in `block in perform!'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/model.rb:268:in `each'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/model.rb:268:in `perform!'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/lib/backup/cli.rb:156:in `perform'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bundler/gems/backup-4057a4b2dac8/bin/backup:5:in `<top (required)>'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bin/backup:23:in `load'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bin/backup:23:in `<main>'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
[2015/10/04 00:23:23][error]   /home/rails/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
[2015/10/04 00:23:23][info] Sending notification using Notifier::Mail...
```

Looks like gem tries to store into different storages simultaneously and get error when moved file Local during storing to FTP. This part:

```
[2015/10/03 22:10:17][info] Storage::FTP Started...
[2015/10/03 22:10:58][info] Storing 'ftp.selcdn.ru:backup/r46_a00/shard00/2015.10.03.21.30.06/shard00.tar'...
[2015/10/03 23:25:51][info] Storage::SFTP Started...
[2015/10/03 23:25:52][info] Storing 'hackday.ru:backup/r46_a00/shard00/2015.10.03.21.30.06/shard00.tar'...
[2015/10/04 00:23:23][info] Cycling Started...
[2015/10/04 00:23:23][info] Storage::SFTP Finished!
[2015/10/04 00:23:23][info] Storage::Local Started...
[2015/10/04 00:23:23][info] Storing '/home/rails/backups/r46_a00/shard00/2015.10.03.21.30.06/shard00.tar'...
[2015/10/04 00:23:23][info] Cycling Started...
[2015/10/04 00:23:23][info] Removing backup package dated 2015.09.28.21.30.14...
[2015/10/04 00:23:23][info] Storage::Local Finished!
[2015/10/04 00:23:23][error] Model::Error: Backup for R46 shard 00 (shard00) Failed!
```

My configuration:

```
Backup::Model.new(:shard00, 'R46 shard 00') do
#  split_into_chunks_of 1000

  database PostgreSQL do |db|
    ...
  end

  # Using default config from config.rb
  store_with FTP do |server|
  end

  store_with SFTP do |server|
  end

  store_with Local do |local|
    local.keep = 5
  end


  compress_with Gzip

  notify_by Mail do |mail|
  end

   notify_by Pushover do |pushover|
   end

end
```

**Comment by tombruijn** [comment]
Hi again @noff !

That doesn't seem right. I think that it should wait until the FTP one is finished before moving on to the next one. Does it happen on every backup run? Is FTP taking longer than usual? Related to the timeout issue? 

There a check in the Local storage you could temporarily misuse to avoid this. If you change the order of the storages in such a way that Local is no the last one defined. This will throw a warning and take up some more space, but it will not move the package, instead it will copy it. For more information about the warning that will be thrown see the [Local storage class](https://github.com/backup/backup/blob/404f3b48069daf6484eac69ce85b26cac70985e7/lib/backup/storage/local.rb#L52-L56)

**Comment by noff** [comment]
No. It happens first time as I see. Not related to the timeout issue.
There wasn't any warnings about Local.

**Comment by tombruijn** [comment]
@noff you'll get a warning when you move the local storage config above one of the other storages in your model file.

```
  # Move Local here
  store_with Local do |local|
  end

  store_with FTP do |server|
  end

  store_with SFTP do |server|
  end

  # Was here
  store_with Local do |local|
  end
```

But it keep occurring?

**Comment by noff** [comment]
Don't occur now. I will notify you if it happens. Thanks.

**Comment by noff** [comment]
Happened today: https://gist.github.com/noff/52b906bb2b1d42b204c7
