### ISSUE TITLE
It is necessary to update dropbox-sdk version

### ISSUE THREAD

**Issue by must-not-code** [backup/backup#762]
I have received the letter from api-support@dropbox.com

> We're writing to you because our logs indicate that you have at least one Dropbox API app using an old version of the Ruby Core SDK, with an out of date certificate file. 
> 
> The Dropbox Ruby Core SDK implements certificate pinning, based on a list of certificates included in the SDK, in order to help secure the connection to the Dropbox API servers.
> 
> On August 1st, 2016, the Dropbox API servers will be updated to use a new certificate, so you’ll need to update the version of the SDK used in your app to match. The latest version of the Ruby Core SDK already contains the updated certificate file:
> 
> [https://www.dropbox.com/developers-v1/core/sdks/ruby](https://www.dropbox.com/developers-v1/core/sdks/ruby)
> 
> You can refer to the CHANGELOG file included in the SDK for a list of changes.
> 
> Please update your app to use the latest SDK by 8/1/16 to ensure continued access to the Dropbox API.

**Comment by tomash** [comment]
Submitted a pull request. Can you test if backup from branch https://github.com/tomash/backup/tree/update-dropbox-gem with dropbox-sdk 1.6.5 works for you?

**Comment by must-not-code** [comment]
I have tried and received an error:
```
Model::Error: Backup for foo.com backup (foo_backup) Failed!
--- Wrapped Exception ---
Storage::Dropbox::Error: Upload Failed!
--- Wrapped Exception ---
NoMethodError: undefined method `parse_response' for #<DropboxClient:0x94faafc>

Backtrace:
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/storage/dropbox.rb:223:in `upload'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/storage/dropbox.rb:123:in `block (3 levels) in transfer!'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/storage/dropbox.rb:140:in `with_retries'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/storage/dropbox.rb:122:in `block (2 levels) in transfer!'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/storage/dropbox.rb:119:in `open'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/storage/dropbox.rb:119:in `block in transfer!'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/storage/dropbox.rb:113:in `each'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/storage/dropbox.rb:113:in `transfer!'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/storage/base.rb:45:in `perform!'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/model.rb:334:in `block in store!'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/model.rb:332:in `map'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/model.rb:332:in `store!'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/model.rb:306:in `block in procedures'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/model.rb:269:in `block in perform!'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/model.rb:268:in `each'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/model.rb:268:in `perform!'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/cli.rb:156:in `perform'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
  /home/dev/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/bin/backup:5:in `<top (required)>'
  /home/dev/.rvm/gems/ruby-2.3.0/bin/backup:23:in `load'
  /home/dev/.rvm/gems/ruby-2.3.0/bin/backup:23:in `<main>'
  /home/dev/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
  /home/dev/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by tomash** [comment]
Seems that `parse_response` became a module method. I've updated my branch, can you test again?

I'll set up my own test harness for this later today (or tomorrow).

**Comment by must-not-code** [comment]
Probably you have forgotten to push changes.

**Comment by tomash** [comment]
Ooops, pushed to wrong repo. Try now.

**Comment by must-not-code** [comment]
Backup has been completed successfully. Thanks.
