### ISSUE TITLE
Use mysqldump options

### ISSUE THREAD

**Issue by oleynikd** [backup/backup#764]
Hi,

First of all, thank you for such a great tool.

How can I pass options to mysqldump? I need to add `--protocol=tcp` cuz I'm using docker and the's no direct socket

Thanks.

**Comment by tombruijn** [comment]
hi @oleynikd, Using `additional_options` you can set any other options to the mysqldump command

```ruby
Model.new(:my_backup, 'My Backup') do
  database MySQL do |db|
    db.additional_options = ["--protocol=tcp"]
  end
end
```

**Comment by oleynikd** [comment]
Thanks, but I tried that...
When I run:
```
mysqldump -h localhost -P 3306 -u root -p*** --protocol=tcp mydb
```
it works great. But this:
```ruby
database MySQL do |db|
    db.name = "mydb"
    db.username = "root"
    db.password = "***"
    db.host = "localhost"
    db.port = 3306
    db.additional_options = ["--protocol=tcp"]
end
```

produces an error:
```
[2016/04/24 15:17:33][error] --- Wrapped Exception ---
[2016/04/24 15:17:33][error] Database::MySQL::Error: Dump Failed!
[2016/04/24 15:17:33][error]   The following system errors were returned:
[2016/04/24 15:17:33][error]   Errno::EPERM: Operation not permitted - 'mysqldump' returned exit code: 1
[2016/04/24 15:17:33][error]
[2016/04/24 15:17:33][error] Backtrace:
[2016/04/24 15:17:33][error]   /var/lib/gems/2.2.0/gems/backup-4.2.3/lib/backup/database/mysql.rb:97:in `perform!'
[2016/04/24 15:17:33][error]   /var/lib/gems/2.2.0/gems/backup-4.2.3/lib/backup/model.rb:269:in `each'
[2016/04/24 15:17:33][error]   /var/lib/gems/2.2.0/gems/backup-4.2.3/lib/backup/model.rb:269:in `block in perform!'
[2016/04/24 15:17:33][error]   /var/lib/gems/2.2.0/gems/backup-4.2.3/lib/backup/model.rb:268:in `each'
[2016/04/24 15:17:33][error]   /var/lib/gems/2.2.0/gems/backup-4.2.3/lib/backup/model.rb:268:in `perform!'
[2016/04/24 15:17:33][error]   /var/lib/gems/2.2.0/gems/backup-4.2.3/lib/backup/cli.rb:156:in `perform'
[2016/04/24 15:17:33][error]   /var/lib/gems/2.2.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2016/04/24 15:17:33][error]   /var/lib/gems/2.2.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2016/04/24 15:17:33][error]   /var/lib/gems/2.2.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2016/04/24 15:17:33][error]   /var/lib/gems/2.2.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2016/04/24 15:17:33][error]   /var/lib/gems/2.2.0/gems/backup-4.2.3/bin/backup:5:in `<top (required)>'
[2016/04/24 15:17:33][error]   /usr/local/bin/backup:23:in `load'
[2016/04/24 15:17:33][error]   /usr/local/bin/backup:23:in `<main>'
```

Any idea why?
Thanks.

**Comment by oleynikd** [comment]
Please help!

**Comment by tombruijn** [comment]
I'm not quite sure what the problem is. I'm able to run your configuration. The TCP protocol setting doesn't seem to cause the issue. It looks like the mysqldump tool is returning the error here, but I don't know why.

You're running mysql in a docker container? Any public image you're using?

**Comment by oleynikd** [comment]
@tombruijn I'm using [Docker's official mysql image ](https://hub.docker.com/_/mysql/) version 5.6
Here's the [Dockerfile](https://github.com/docker-library/mysql/blob/d7e71447ff3ad3c579ac3cca8c0dc090d11d4baf/5.6/Dockerfile)

I'm running `backup` from host... It's Ubuntu 14.04.4. `mysqldump --version`:
```
mysqldump  Ver 10.13 Distrib 5.5.47, for debian-linux-gnu (x86_64)
```

Once more: running `mysqldump` manually from host works great.
Maybe there's some way to see more verbose error output?

Thanks.

**Comment by tombruijn** [comment]
You can always try to configure the logger to output more information: http://backup.github.io/backup/v4/logging/

It should already throw the entire STDERR on error, but try to activate the STDOUT as well or write everything to syslog instead.

I'm not much help right now with testing the docker setup unfortunately
