### ISSUE TITLE
S3 Bucket Storage Path

### ISSUE THREAD

**Issue by rili** [backup/backup#778]
Hi,
i am using Backup and S3 for the first time, and i got stuck... The backup test seems not to be working, so after i execute the following:

`backup perform -t production_backup`

i get the following log:

> [2016/05/31 18:27:41][info] Database::PostgreSQL Started...
[2016/05/31 18:27:41][info] Using Compressor::Gzip for compression.
[2016/05/31 18:27:41][info]   Command: '/bin/gzip'
[2016/05/31 18:27:41][info]   Ext: '.gz'
[2016/05/31 18:27:41][info] Database::PostgreSQL Finished!
[2016/05/31 18:27:41][info] Creating Archive 'app_archive'...
[2016/05/31 18:27:41][info] Running system utility 'tar'...
[2016/05/31 18:27:41][info] tar:STDOUT: tar (GNU tar) 1.27.1
[2016/05/31 18:27:41][info] tar:STDOUT: Copyright (C) 2013 Free Software Foundation, Inc.
[2016/05/31 18:27:41][info] tar:STDOUT: License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
[2016/05/31 18:27:41][info] tar:STDOUT: This is free software: you are free to change and redistribute it.
[2016/05/31 18:27:41][info] tar:STDOUT: There is NO WARRANTY, to the extent permitted by law.
[2016/05/31 18:27:41][info] tar:STDOUT: 
[2016/05/31 18:27:41][info] tar:STDOUT: Written by John Gilmore and Jay Fenlason.
[2016/05/31 18:27:41][info] Using Compressor::Gzip for compression.
[2016/05/31 18:27:41][info]   Command: '/bin/gzip'
[2016/05/31 18:27:41][info]   Ext: '.gz'
[2016/05/31 18:28:03][info] Archive 'app_archive' Complete!
[2016/05/31 18:28:03][info] Packaging the backup files...
[2016/05/31 18:28:03][info] Splitter configured with a chunk size of 250MB and suffix length of 3.
[2016/05/31 18:28:03][info] Packaging Complete!
[2016/05/31 18:28:03][info] Cleaning up the temporary files...
[2016/05/31 18:28:04][info] Storage::S3 Started...
[2016/05/31 18:28:04][info] Storing 'db-backups-backups/production/production_backup/2016.05.31.18.27.41/production_backup.tar'...
[2016/05/31 18:28:04][info]   Initiate Multipart 'db-backups-backups/production/production_backup/2016.05.31.18.27.41/production_backup.tar'
[2016/05/31 18:28:04][info] CloudIO::Error: Retry #1 of 10
[2016/05/31 18:28:04][info]   Operation: POST 'db-backups-backups/production/production_backup/2016.05.31.18.27.41/production_backup.tar' (Initiate)
[2016/05/31 18:28:04][info] --- Wrapped Exception ---
[2016/05/31 18:28:04][info] TypeError: no implicit conversion of Array into String

after nine more atempts...

> [2016/05/31 18:32:34][info] CloudIO::Error: Retry #10 of 10
[2016/05/31 18:32:34][info]   Operation: POST 'db-backups-backups/production/production_backup/2016.05.31.18.27.41/production_backup.tar' (Initiate)
[2016/05/31 18:32:34][info] --- Wrapped Exception ---
[2016/05/31 18:32:34][info] TypeError: no implicit conversion of Array into String
[2016/05/31 18:33:04][error] Model::Error: Backup for Production Backup (production_backup) Failed!
[2016/05/31 18:33:04][error] --- Wrapped Exception ---
[2016/05/31 18:33:04][error] CloudIO::Error: Max Retries (10) Exceeded!
[2016/05/31 18:33:04][error]   Operation: POST 'db-backups-backups/production/production_backup/2016.05.31.18.27.41/production_backup.tar' (Initiate)
[2016/05/31 18:33:04][error]   Be sure to check the log messages for each retry attempt.
[2016/05/31 18:33:04][error] --- Wrapped Exception ---
[2016/05/31 18:33:04][error] TypeError: no implicit conversion of Array into String
[2016/05/31 18:33:04][error] 
[2016/05/31 18:33:04][error] Backtrace:
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fog-aws-0.1.1/lib/fog/aws/signaturev4.rb:12:in `+'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fog-aws-0.1.1/lib/fog/aws/signaturev4.rb:12:in `initialize'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fog-aws-0.1.1/lib/fog/aws/storage.rb:509:in `new'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fog-aws-0.1.1/lib/fog/aws/storage.rb:509:in `setup_credentials'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fog-aws-0.1.1/lib/fog/aws/storage.rb:492:in `initialize'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fog-core-1.29.0/lib/fog/core/service.rb:115:in `new'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fog-core-1.29.0/lib/fog/core/service.rb:115:in `new'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/fog-core-1.29.0/lib/fog/storage.rb:25:in `new'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/cloud_io/s3.rb:136:in `connection'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/cloud_io/s3.rb:157:in `block in initiate_multipart'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/cloud_io/base.rb:21:in `with_retries'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/cloud_io/s3.rb:156:in `initiate_multipart'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/cloud_io/s3.rb:48:in `upload'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/storage/s3.rb:109:in `block in transfer!'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/storage/s3.rb:105:in `each'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/storage/s3.rb:105:in `transfer!'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/storage/base.rb:45:in `perform!'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/model.rb:334:in `block in store!'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/model.rb:332:in `map'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/model.rb:332:in `store!'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/model.rb:306:in `block in procedures'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/model.rb:269:in `call'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/model.rb:269:in `block in perform!'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/model.rb:268:in `each'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/model.rb:268:in `perform!'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/lib/backup/cli.rb:156:in `perform'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backup-4.2.3/bin/backup:5:in `<top (required)>'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/bin/backup:23:in `load'
[2016/05/31 18:33:04][error]   /home/deploy/.rbenv/versions/2.2.0/bin/backup:23:in `<main>'
[2016/05/31 18:33:04][warn] Cleaner::Error: Cleanup Warning
[2016/05/31 18:33:04][warn]   The temporary backup folder '/home/deploy/Backup/.tmp'
[2016/05/31 18:33:04][warn]   appears to contain the backup files which were to be stored:
[2016/05/31 18:33:04][warn]   /home/deploy/Backup/.tmp/production_backup.tar
[2016/05/31 18:33:04][warn]   
[2016/05/31 18:33:04][warn]   Make sure you check these files before the next scheduled backup for
[2016/05/31 18:33:04][warn]   'Production Backup (production_backup)'
[2016/05/31 18:33:04][warn]   These files will be removed at that time!
[2016/05/31 18:33:04][info] Sending notification using Notifier::Mail...

My Backup config script:

`Model.new(:production_backup, 'Production Backup') do

  split_into_chunks_of 250

  compress_with Gzip

  database PostgreSQL do |db|
    db.name               = "my_db"
    db.username           = "deploy"
    db.password           =  ENV["DB_PASSWORD"]
    db.host               = "localhost"
    db.port               = 5432
    db.additional_options = ["-xc", "-E=utf8"]
  end

  archive :app_archive do |archive|
    archive.add '/home/deploy/my_rails_app/'
  end

  store_with S3 do |s3|
    s3.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    s3.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY_ID'],
    s3.region = "eu-central-1"
    s3.bucket = ENV['AWS_BUCKET_BACKUPS']
    s3.path = "production"
  end

  notify_by Mail do |mail|
   ...
  end

end`

Hope someone can give me a hint. Thanks in advance

**Comment by rili** [comment]
hmm i already found the error... i had a point after the s3.secret_access_key

`s3.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY_ID'],
`

:(
