### ISSUE TITLE
Errno::EPERM: Operation not permitted - 'innobackupex' returned exit code: 1

### ISSUE THREAD

**Issue by mdahiemstra** [backup/backup#783]
Hi,

I am getting the following error response from the gem:
`Errno::EPERM: Operation not permitted - 'innobackupex' returned exit code: 1`

I have tried to debug this myself, but I'm getting a little stuck. Ruby is not my primary programming language ^^

My model is very simple:

```
Model.new(:sites_data, 'MySQL sites data') do
  database MySQL do |db|
    db.backup_engine      = :innobackupex
    db.name               = ""
    db.username           = "xtrabackup"
    db.password           = "toor"
    db.host               = "percona1"
    db.port               = 3306
    db.skip_tables        = []
    db.only_tables        = []
  end

  store_with Local do |local|
    local.path = '/backups/'
    local.keep = 5
  end
end
```

The full response from backup:

```
[2016/06/22 13:04:46][info] Performing Backup for 'MySQL sites data (sites_data)'!
[2016/06/22 13:04:46][info] [ backup 4.2.3 : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux] ]
[2016/06/22 13:04:46][info] Database::MySQL Started...
[2016/06/22 13:04:47][error] Model::Error: Backup for MySQL sites data (sites_data) Failed!
[2016/06/22 13:04:47][error] --- Wrapped Exception ---
[2016/06/22 13:04:47][error] Database::MySQL::Error: Dump Failed!
[2016/06/22 13:04:47][error]   The following system errors were returned:
[2016/06/22 13:04:47][error]   Errno::EPERM: Operation not permitted - 'innobackupex' returned exit code: 1
[2016/06/22 13:04:47][error]
[2016/06/22 13:04:47][error] Backtrace:
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/database/mysql.rb:99:in `perform!'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/model.rb:269:in `each'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/model.rb:269:in `block in perform!'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/model.rb:268:in `each'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/model.rb:268:in `perform!'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/lib/backup/cli.rb:156:in `perform'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/gems/backup-4.2.3/bin/backup:5:in `<top (required)>'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/bin/backup:23:in `load'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/bin/backup:23:in `<main>'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
[2016/06/22 13:04:47][error]   /backups/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
[2016/06/22 13:04:47][warn] Cleaner::Error: Cleanup Warning
[2016/06/22 13:04:47][warn]   The temporary packaging folder still exists!
[2016/06/22 13:04:47][warn]   '/backups/Backup/.tmp/sites_data'
[2016/06/22 13:04:47][warn]   This folder may contain completed Archives and/or Database backups.
[2016/06/22 13:04:47][warn]
[2016/06/22 13:04:47][warn]   Make sure you check these files before the next scheduled backup for
[2016/06/22 13:04:47][warn]   'MySQL sites data (sites_data)'
[2016/06/22 13:04:47][warn]   These files will be removed at that time!
```

I logged the command where I thought stuff was going bad:

```
/usr/bin/innobackupex --user=xtrabackup --password=toor --host='percona1' --port='3306'  --no-timestamp /backups/Backup/.tmp/sites_data/databases/MySQL.bkpdir  2> /dev/null  && /usr/bin/innobackupex --apply-log /backups/Backup/.tmp/sites_data/databases/MySQL.bkpdir    2> /dev/null  && /bin/tar --remove-files -cf -  -C /backups/Backup/.tmp/sites_data/databases MySQL.bkpdir
```

But when I run this command manually (as the same user I run backup with) it is succesfull.

I strongly believe this is an application error somewhere, could someone point me in the right direction?

I am using Ruby 2.3.0 installed through RVM and backup 4.2.3

**Comment by tombruijn** [comment]
Hi @mdahiemstra , is backup being run under the same user account when you run it manually?

The error "Operation not permitted" is not a backup error. The OS is throwing that error. So the user account that's executing the command has no access to perform it.
