### ISSUE TITLE
SFTP backup erroring with "no such file"

### ISSUE THREAD

**Issue by fredsted** [backup/backup#816]
## What went wrong?

Recently, my backup model started giving errors after each backup. I don't think anything has changed. 

As you can see from the log, it looks like Backupv4 tries to find the file it uploaded, after uploading – but can't.

However, If I ssh into the server right after it's uploaded, I can find the exact file it says "no such file" to.

```
[2016/12/12 07:30:56][info] Storage::SFTP Started...
[2016/12/12 07:30:57][info] Storing '10.10.10.15:backups/backup_name/2016.12.12.07.30.02/backup_name.tar'...
[2016/12/12 07:31:43][info] Storage::SFTP Finished!
[2016/12/12 07:31:43][error] Model::Error: Backup for General backupv4 model (backup_name) Failed!
[2016/12/12 07:31:43][error] --- Wrapped Exception ---
[2016/12/12 07:31:43][error] Net::SFTP::StatusException open /backup_name/2016.12.12.07.30.02/backup_name.tar (2, "no such file")
[2016/12/12 07:31:43][error] 
[2016/12/12 07:31:43][error] Backtrace:
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:321:in `on_open'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:87:in `call'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:87:in `respond_to'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:948:in `dispatch_request'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:911:in `when_channel_polled'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:311:in `call'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:311:in `process'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `block in preprocess'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `each'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `preprocess'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:203:in `wait'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:103:in `upload!'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/storage/sftp.rb:42:in `block (2 levels) in transfer!'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/storage/sftp.rb:38:in `each'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/storage/sftp.rb:38:in `block in transfer!'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/storage/sftp.rb:31:in `block in connection'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `call'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `block in do_version'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `each'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:939:in `do_version'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:909:in `when_channel_polled'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:311:in `call'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:311:in `process'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `block in preprocess'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `each'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:223:in `preprocess'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:787:in `connect!'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/net-sftp-2.1.2/lib/net/sftp.rb:32:in `start'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/storage/sftp.rb:29:in `connection'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/storage/sftp.rb:35:in `transfer!'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/storage/base.rb:45:in `perform!'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/model.rb:334:in `block in store!'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/model.rb:332:in `map'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/model.rb:332:in `store!'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/model.rb:306:in `block in procedures'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/model.rb:269:in `call'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/model.rb:269:in `block in perform!'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/model.rb:268:in `each'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/model.rb:268:in `perform!'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/lib/backup/cli.rb:156:in `perform'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2016/12/12 07:31:43][error]   /var/lib/gems/2.1.0/gems/backup-4.2.3/bin/backup:5:in `<top (required)>'
[2016/12/12 07:31:43][error]   /usr/local/bin/backup:23:in `load'
[2016/12/12 07:31:43][error]   /usr/local/bin/backup:23:in `<main>'
```

## What steps did you follow?

I've tried disabling removal of old backups, e.g. commenting out server.keep.

## How is your copy of backup configured?

Here's the SFTP part of the model that fails:

```
  store_with SFTP do |server|
    server.username = 'remotebackup'
    server.password = 'censored'
    server.ip       = '10.10.10.15'
    server.port     = 22
    server.path     = '~/backups'
    # Use a number or a Time object to specify how many backups to keep.
    # server.keep     = Time.now - 60 * 60 * 24 * 25 # Keep not neccessary; we clean automatically on the server

    # Additional options for the SSH connection.
    # server.ssh_options = {}
  end
```

Here's `config.rb`:

```
# encoding: utf-8

##
# Backup v4.x Configuration
#
# Documentation: http://backup.github.io/backup
# Issue Tracker: https://github.com/backup/backup/issues

##
# Logging
#
# Logging options may be set on the command line, but certain settings
# may only be configured here.
#

Logger.configure do
  console.quiet     = true            # Same as command line: --quiet
  logfile.max_bytes = 2_000_000       # Default: 500_000
  syslog.enabled    = true            # Same as command line: --syslog
  syslog.ident      = 'backup_name' # Default: 'backup'
end
```

## Tell us about the computer that runs the backup gem

* Operating system: Ubuntu Server 14.04.3ruby 
* Ruby version: 2.1.7p400
* Tools or services used by backup: Redis, mySQL, SFTP, Gzip, Mail

**Comment by yosephbernandus** [comment]
@fredsted Hey is there a way to fix this? because I get same problem
