### ISSUE TITLE
Backups to Dropbox Failing TypeError: can't convert OpenSSL::SSL::SSLError into String

### ISSUE THREAD

**Issue by shakycode** [backup/backup#840]
## What went wrong?

````
[2017/02/28 17:00:30][info] Session data loaded from cache!
[2017/02/28 17:00:30][info] Storage::Dropbox::Error: Retry #1 of 10.
[2017/02/28 17:00:30][info] --- Wrapped Exception ---
[2017/02/28 17:00:30][info] TypeError: can't convert OpenSSL::SSL::SSLError into String
[2017/02/28 17:01:00][info] Storage::Dropbox::Error: Retry #2 of 10.
[2017/02/28 17:01:00][info] --- Wrapped Exception ---
[2017/02/28 17:01:00][info] TypeError: can't convert OpenSSL::SSL::SSLError into String
[2017/02/28 17:01:30][info] Storage::Dropbox::Error: Retry #3 of 10.
[2017/02/28 17:01:30][info] --- Wrapped Exception ---
[2017/02/28 17:01:30][info] TypeError: can't convert OpenSSL::SSL::SSLError into String
[2017/02/28 17:02:01][info] Storage::Dropbox::Error: Retry #4 of 10.
[2017/02/28 17:02:01][info] --- Wrapped Exception ---
[2017/02/28 17:02:01][info] TypeError: can't convert OpenSSL::SSL::SSLError into String
[2017/02/28 17:02:31][info] Storage::Dropbox::Error: Retry #5 of 10.
[2017/02/28 17:02:31][info] --- Wrapped Exception ---
[2017/02/28 17:02:31][info] TypeError: can't convert OpenSSL::SSL::SSLError into String
[2017/02/28 17:03:01][info] Storage::Dropbox::Error: Retry #6 of 10.
[2017/02/28 17:03:01][info] --- Wrapped Exception ---
[2017/02/28 17:03:01][info] TypeError: can't convert OpenSSL::SSL::SSLError into String
[2017/02/28 17:03:31][info] Storage::Dropbox::Error: Retry #7 of 10.
[2017/02/28 17:03:31][info] --- Wrapped Exception ---
[2017/02/28 17:03:31][info] TypeError: can't convert OpenSSL::SSL::SSLError into String
[2017/02/28 17:04:01][info] Storage::Dropbox::Error: Retry #8 of 10.
[2017/02/28 17:04:01][info] --- Wrapped Exception ---
[2017/02/28 17:04:01][info] TypeError: can't convert OpenSSL::SSL::SSLError into String
[2017/02/28 17:04:31][info] Storage::Dropbox::Error: Retry #9 of 10.
[2017/02/28 17:04:31][info] --- Wrapped Exception ---
[2017/02/28 17:04:31][info] TypeError: can't convert OpenSSL::SSL::SSLError into String
[2017/02/28 17:05:01][info] Storage::Dropbox::Error: Retry #10 of 10.
[2017/02/28 17:05:01][info] --- Wrapped Exception ---
[2017/02/28 17:05:01][info] TypeError: can't convert OpenSSL::SSL::SSLError into String
[2017/02/28 17:05:31][error] Model::Error: Backup for logiccad backup (prod_backup) Failed!
[2017/02/28 17:05:31][error] --- Wrapped Exception ---
[2017/02/28 17:05:31][error] Storage::Dropbox::Error: Upload Failed!
[2017/02/28 17:05:31][error] --- Wrapped Exception ---
[2017/02/28 17:05:31][error] TypeError: can't convert OpenSSL::SSL::SSLError into String
[2017/02/28 17:05:31][error] 
[2017/02/28 17:05:31][error] Backtrace:
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dropbox-sdk-1.5.1/lib/dropbox_sdk.rb:52:in `+'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dropbox-sdk-1.5.1/lib/dropbox_sdk.rb:52:in `rescue in do_http'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dropbox-sdk-1.5.1/lib/dropbox_sdk.rb:47:in `do_http'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dropbox-sdk-1.5.1/lib/dropbox_sdk.rb:106:in `do_http_with_body'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dropbox-sdk-1.5.1/lib/dropbox_sdk.rb:118:in `do_put'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dropbox-sdk-1.5.1/lib/dropbox_sdk.rb:500:in `partial_chunked_upload'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/storage/dropbox.rb:224:in `upload'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/storage/dropbox.rb:123:in `block (3 levels) in transfer!'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/storage/dropbox.rb:140:in `with_retries'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/storage/dropbox.rb:122:in `block (2 levels) in transfer!'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/storage/dropbox.rb:119:in `open'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/storage/dropbox.rb:119:in `block in transfer!'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/storage/dropbox.rb:113:in `each'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/storage/dropbox.rb:113:in `transfer!'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/storage/base.rb:35:in `perform!'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/model.rb:269:in `each'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/model.rb:269:in `block in perform!'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/model.rb:268:in `each'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/model.rb:268:in `perform!'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/lib/backup/cli.rb:156:in `perform'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/backup-4.1.10/bin/backup:5:in `<top (required)>'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/bin/backup:23:in `load'
[2017/02/28 17:05:31][error]   /home/deploy/.rbenv/versions/1.9.3-p194/bin/backup:23:in 
````

As of 1am this morning our backups to dropbox started failing.  With the error `OpenSSL::SSL::SSLError into String`

We have been experiencing no problems until this morning.  We are on Ubuntu 16.04LTS, Ruby 1.9.3-p194, and backup gem v 4.1.10.

We've made not system patches or changed any configuration in the last 24 hours.

Our config.rb is commented out, but here's a sanitized copy of our backup model file

**prod_backup,rb**

````
# encoding: utf-8

##
# Backup Generated: prod_backup
# Once configured, you can run the backup with the following command:
#
# $ backup perform -t prod_backup [-c <path_to_configuration_file>]
#
# For more information about Backup's components, see the documentation at:
# http://backup.github.io/backup
#
Model.new(:prod_backup, 'logiccad backup') do
  ##
  # Archive [Archive]
  #
  # Adding a file or directory (including sub-directories):
  #   archive.add "/path/to/a/file.rb"
  #   archive.add "/path/to/a/directory/"
  #
  # Excluding a file or directory (including sub-directories):
  #   archive.exclude "/path/to/an/excluded_file.rb"
  #   archive.exclude "/path/to/an/excluded_directory
  #
  # By default, relative paths will be relative to the directory
  # where `backup perform` is executed, and they will be expanded
  # to the root of the filesystem when added to the archive.
  #
  # If a `root` path is set, relative paths will be relative to the
  # given `root` path and will not be expanded when added to the archive.
  #
  #   archive.root '/path/to/archive/root'
  #
#  archive :my_archive do |archive|
#    # Run the `tar` command using `sudo`
#    # archive.use_sudo
#    archive.add "/path/to/a/file.rb"
#    archive.add "/path/to/a/folder/"
#    archive.exclude "/path/to/a/excluded_file.rb"
#    archive.exclude "/path/to/a/excluded_folder"
#  end

  database PostgreSQL do |db|
    # To dump all databases, set `db.name = :all` (or leave blank)
    db.name               = "app_production"
    db.username           = "user"
    db.password           = "password"
    db.host               = "localhost"
    db.port               = 5432
    #db.socket             = "/tmp/pg.sock"
    db.sudo_user	  = "deploy"
    # When dumping all databases, `skip_tables` and `only_tables` are ignored.
#    db.skip_tables        = ['skip', 'these', 'tables']
#    db.only_tables        = ['only', 'these' 'tables']
#    db.additional_options = []
  end

  ##
  # Local (Copy) [Storage]
  #
  #store_with Local do |local|
  #  local.path       = "~/backups/"
  #  local.keep       = 24
  #end
  store_with Dropbox do |db|
  db.api_key     = "apikey"
  db.api_secret  = "secretkey"
  # Sets the path where the cached authorized session will be stored.
  # Relative paths will be relative to ~/Backup, unless the --root-path
  # is set on the command line or within your configuration file.
  db.cache_path  = ".cache"
  # :app_folder (default) or :dropbox
  db.access_type = :app_folder
  db.path        = "/ambackup"
  # Use a number or a Time object to specify how many backups to keep.
  db.keep        = 24
  end	
  ##
  # Gzip [Compressor]
  #
  compress_with Gzip

  ##
  # Mail [Notifier]
  #
  # The default delivery method for Mail Notifiers is 'SMTP'.
  # See the documentation for other delivery options.
  #
  notify_by Mail do |mail|
    mail.on_success           = true
    mail.on_warning           = true
    mail.on_failure           = true

    mail.from                 = "ambackups@gmail.com"
    mail.to                   = "user@domain.com"
    mail.address              = "smtp.gmail.com"
    mail.port                 = 587
    mail.domain               = "gmail.com"
    mail.user_name            = "ambackups@gmail.com"
    mail.password             = "password"
    mail.authentication       = "plain"
    mail.encryption           = :starttls
  end
  #Slack Notifier
  notify_by Slack do |slack|
  slack.on_success = true
  slack.on_warning = true
  slack.on_failure = true

  # The integration token
  slack.webhook_url = 'https://hooks.slack.com/services/APIHOOKKEY'

  ##
  # Optional
  #
  # The channel to which messages will be sent
  # slack.channel = 'my_channel'
  #
  # The username to display along with the notification
  # slack.username = 'my_username'
  #
  # The emoji icon to use for notifications.
  # See http://www.emoji-cheat-sheet.com for a list of icons.
  # slack.icon_emoji = ':ghost:'
  #
  # Change default notifier message.
  # See https://github.com/backup/backup/pull/698 for more information.
  # slack.message = lambda do |model, data|
  #   "[#{data[:status][:message]}] #{model.label} (#{model.trigger})"
  # end
end
````

**Comment by stuartellis** [comment]
Hmm.

If you haven't changed anything on your server, and it worked before, then it's possible that something has changed on the Dropbox end to break the SSL. For example, a change of server certificate or the cyphers that they support. I don't see anything obvious from a glance at their blog and the GitHub issues for the Ruby Dropbox SDK. If you are a paying customer then you could certainly try contacting their support.

It may not be relevant here, but I would recommend upgrading from Ruby 1.9.3: it looks like Ubuntu now ship 2.3.0, and 1.9.3 is not supported by the Ruby team.

**Comment by shakycode** [comment]
@stuartellis Thanks for chiming in.  I'm providing all the information to Dropbox support as we are a paying customer.  Agreed on the ruby 1.9.3 but we are locked in our current app server on this until we have time to upgrade to a new ruby MRI that is compatible with our version of rails.

I will close this and work with dropbox.

**Comment by shakycode** [comment]
@stuartellis I just heard from dropbox and they said the issue is the the Ruby SDK that backup is using is relying on API V1 which is deprecated.  They said to upgrade to the new SDK and use V2 to get functionality back.  Looks like we'll need to do a new PR and version that supports the dropbox V2 API

**Comment by stuartellis** [comment]
@shakycode - Just to clarify, did they say that they have broken compatibility with the v1 API and Ruby SDK, or just that they would not support you if used them?

**Comment by sknoslo** [comment]
@shakycode @stuartellis I got an email from Dropbox in April 2016 saying the certificate included with my version of the dropbox-sdk was out dated and would stop working in August 2016. The backup I was doing was non essential so I just put it off until it broke... which was 2/28, same as you. I can confirm that updating backup and the dropbox-sdk fixed the problem. Not sure what the ruby version requirements are for either of these gems though. Hope that helps.

**Comment by shakycode** [comment]
@sknoslo Thanks for the feedback, I will try upgrading and see what happens, but in reality for backup to support their V2 API we are going to need to do a PR on this.

@stuartellis They said that the v1 API has been soft deprecated as of last June and that they no longer support a Ruby SDK for dropbox, instead telling me that we will need the gem to make direct API calls instead of using a ruby wrapper or SDK.

For the meantime until I have time to work on getting API V2 to work, I've moved my storage to amazon s3 which has no deprecation in the forseeable future.

**Comment by sknoslo** [comment]
@shakycode correct, this June, backups to Dropbox should stop working entirely if `backup` isn't updated to V2.

**Comment by shakycode** [comment]
@sknoslo yes sir, so I'm going to try to write a new fork of backup that supports API v2 but I don't think we will need backwards compatibility since the API v1 and ruby sdk is being deprecated.

@stuartellis Thoughts?

**Comment by stuartellis** [comment]
The current version of Backup uses the last release of the dropbox-sdk gem (1.6.5). @sknoslo: Would you mind confirming the versions that you are using?

I'm neutral, since I don't use Dropbox. If we have a replacement plugin, then somebody will probably find that useful, but I think that S3 and equivalents are a better choice in most cases, so I wouldn't personally be upset to lose it.

**Comment by sknoslo** [comment]
@stuartellis Yes, I have dropbox-sdk 1.6.5 now, with the latest version of backup.

**Comment by simonhutchings** [comment]
Has anyone made a new fork? Everything stopped working for me this morning on 8 servers

**Comment by simonhutchings** [comment]
Solved: gem update backup
The latest version has the new sdk and works fine!!

**Comment by stuartellis** [comment]
If this is something that people are interested in, please do post on #838 or our Gitter channel, and link up with @shakycode, since the current code will stop working on June this year.

I am going to mark this ticket as closed, since we know that the current solution is to use the latest version of Backup, and the long-term solution is #838.
