### ISSUE TITLE
Unable to activate backup-4.2.3, because thor-0.19.4 conflicts with thor (= 0.18.1)

### ISSUE THREAD

**Issue by lichtamberg** [backup/backup#878]
Hi,

I just tried to run backup (4.4.0) on Ubuntu 14.04, ruby 2.3.4 managed via rbenv.
My project uses thor 0.19.4 and seem to influence the backup gem somehow?
Backup *is not added* to my project's Gemfile.

```shell
cd /home/user/apps/project-admin/current && rbenv sudo backup perform --trigger project_hourly --config_file config/backup/config.rb --log-path log --tmp-path /tmp/project_backup_$(date +\%s)
/home/user/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate backup-4.2.3, because thor-0.19.4 conflicts with thor (= 0.18.1) (Gem::ConflictError)
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/backup-4.2.3/lib/backup/logger.rb:3:in `<top (required)>'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/backup-4.2.3/lib/backup.rb:141:in `block in <module:Backup>'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/backup-4.2.3/lib/backup.rb:141:in `each'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/backup-4.2.3/lib/backup.rb:141:in `<module:Backup>'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/backup-4.2.3/lib/backup.rb:25:in `<top (required)>'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/user/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/backup-4.2.3/bin/backup:4:in `<top (required)>'
  from /home/user/.rbenv/versions/2.3.4/bin/backup:22:in `load'
  from /home/user/.rbenv/versions/2.3.4/bin/backup:22:in `<main>'
```

Only when I really unintsall the thor 0.19.4 gem (which is needed in my project though), the backup runs fine...

Do you maybe have any hints?

**Comment by tombruijn** [comment]
I would recommend using bundler for installing and managing dependencies.
When executing it `bundle exec backup perform ...` you shouldn't run into this problem.

I don't think `rbenc sudo backup perform ...` now locks which gem versions it uses, right?

**Comment by lichtamberg** [comment]
But bundle exec needs a Gemfile - and I thought the backup-gem shouldnt be added to the Gemfile?

**Comment by lichtamberg** [comment]
Thanks I found a way:

I've created a new directory, just for backup, added an empty Gemfile with just the proper backup-version and started my backups with:

```
BUNDLE_GEMFILE=/home/user/apps/admin/current/config/backup/Gemfile rbenv sudo bundle exec backup perform --trigger weekly --config_file config.rb --log-path log --tmp-path /tmp/backup_$(date +%s)
```

**Comment by tombruijn** [comment]
@lichtamberg Backup should be added to a Gemfile, just not that one of the parent Ruby app, such as a Rails app. That usually is the reason for a lot of dependency conflicts.
