### ISSUE TITLE
DropboxError: server response does not have offset key

### ISSUE THREAD

**Issue by vtm9** [backup/backup#899]
## What went wrong?

Dropbox storage is not working 
It works for me about 6 months, but now it raise error:
 `DropboxError: server response does not have offset key`
 
## What steps did you follow?

check it with 4.3.0 and 4.4.0 versions

ruby 2.3.3p222
Operating system: Debian GNU/Linux 8.7 (jessie)

Thanks All!

**Comment by simonhutchings** [comment]
I think they have finally turned off api v1 support at dropbox. Has anyone adapted the dropbox script for dropbox_api usage instead of dropbox_sdk gem?

**Comment by vtm9** [comment]
Try to adapted for dropbox_api

**Comment by nuno84** [comment]
Same problem here... is there any switch I can use on the backup script to use the correct api version or will it be necessary to develop something at the backup gem level?
Thank you

**Comment by okliv** [comment]
i have tried to delete dropbox app and recreate all configuration steps from the beginning - now it is even not creating the `.cache/...` file of the session

just gives this:

```
[2017/09/30 09:53:05][info] Creating a new session!
[2017/09/30 09:53:21][error] Model::Error: Backup for MyModel backup (my_model_backup) Failed!
[2017/09/30 09:53:21][error] --- Wrapped Exception ---
[2017/09/30 09:53:21][error] Storage::Dropbox::Error: Upload Failed!
[2017/09/30 09:53:21][error] --- Wrapped Exception ---
[2017/09/30 09:53:21][error] Storage::Dropbox::Error: Authorization Failed
[2017/09/30 09:53:21][error] --- Wrapped Exception ---
[2017/09/30 09:53:21][error] Storage::Dropbox::Error: Could not create or authenticate a new session
[2017/09/30 09:53:21][error] --- Wrapped Exception ---
[2017/09/30 09:53:21][error] DropboxAuthError: Error getting request token.  Is your app key and secret correctly set?  Server returned 400: Bad Request.
```

**Comment by tombruijn** [comment]
The Dropbox API V1 has been recently shutdown and Backup doesn't have support for V2 yet. There's an issue open for it #838 , but it hasn't been fixed yet. @nynhex any update on this?

**Comment by okliv** [comment]
meantime, maybe someone can advice an alternative to dropbox?

official documentation http://backup.github.io/backup/v4/ proposes

        CloudFiles
        Dropbox
        FTP
        Local
        SCP
        SFTP
        RSync
        S3

and only dropbox i could use as a FREE external cloud service (CloudFiles as far as i tried - needs credit card and so on)

- local - not an option at all
- (S)FTP - if my server will be compromised then it will compromise my ftps too over backup setup files (so, again, not really an easy-to-setup option)
- RSync/S3 - never used. looks like need much time to get how and what...

so, for now my backups are stopped and it is, obviously, not good :(

any suggestions?

thanks

**Comment by vtm9** [comment]
I made a working fork with api V2, it's require api_token instead key and secret. Token can be generated in dropbox accout settings. Code is't very good, but it works.  Need to refactor tests. But there too many mocks)) and deep dependency with dropbox-sdk-gem.  May be after I'll refactor them amd make PR. Thanks all! https://github.com/vtm9/backup/tree/dropbox_api_v2

**Comment by lorenso** [comment]
Hi

Gemfile

```
source 'https://rubygems.org'

gem 'backup', github: 'vtm9/backup', branch: 'dropbox_api_v2'
gem 'dropbox_api', github: 'vtm9/dropbox_api', branch: 'chunked_file_uploader'
```

bundle install - ok

but **backup perform -t model_backup**

```
[2017/10/01 09:18:52][error] CLI::Error
[2017/10/01 09:18:52][error] --- Wrapped Exception ---
[2017/10/01 09:18:52][error] NoMethodError: undefined method `api_key=' for #<Backup::Storage::Dropbox:0x00000001553f60>
[2017/10/01 09:18:52][error] Did you mean?  api_token=
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/lib/backup/config/helpers.rb:122:in `method_missing'
[2017/10/01 09:18:52][error] /home/deploy/Backup/models/tavie_backup.rb:30:in `block (3 levels) in load'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/lib/backup/storage/base.rb:40:in `instance_eval'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/lib/backup/storage/base.rb:40:in `initialize'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/lib/backup/storage/dropbox.rb:33:in `initialize'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/lib/backup/model.rb:153:in `new'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/lib/backup/model.rb:153:in `store_with'
[2017/10/01 09:18:52][error] /home/deploy/Backup/models/tavie_backup.rb:29:in `block (2 levels) in load'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/lib/backup/model.rb:127:in `instance_eval'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/lib/backup/model.rb:127:in `initialize'
[2017/10/01 09:18:52][error] /home/deploy/Backup/models/tavie_backup.rb:12:in `new'
[2017/10/01 09:18:52][error] /home/deploy/Backup/models/tavie_backup.rb:12:in `block in load'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/lib/backup/config.rb:48:in `instance_eval'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/lib/backup/config.rb:48:in `block in load'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/lib/backup/config.rb:47:in `each'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/lib/backup/config.rb:47:in `load'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/lib/backup/cli.rb:129:in `perform'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bundler/gems/backup-c6e7aa56be38/bin/backup:5:in `<top (required)>'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bin/backup:22:in `load'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bin/backup:22:in `<main>'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
[2017/10/01 09:18:52][error] /home/deploy/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
```

what to do?

Thx

**Comment by vtm9** [comment]
Hi @lorenso, you need to specify your API token instead api_key and api_secret. Token you can generate in your dropbox account in `apps` tab.

```ruby
  store_with Dropbox do |db|
    db.keep        = 5
    db.retry_waitsec = 1
    db.api_token  = "DROPBOX_TOKEN"
  end
```
This works for me

**Comment by vtm9** [comment]
I made PR in WIP state. It can be merged after 'dropbox_api' gem updated. #901

**Comment by stuartellis** [comment]
@okliv - I think that S3 is by far the best option on that list. Personally, I would not recommend using Dropbox as a backup or archive, or a solution that just transfers data from one machine to another single machine.

**Comment by nynhex** [comment]
@stuartellis @tombruijn I'm trying to find time to integrate the Dropbox API V2 into backup, but due to my time constraints this is slow moving juggling a day job and family.  Happy to continue to work on it, but honestly I think that we should stay away from Dropbox and focus on S3 support.  I've switched all of my backups with the gem to S3 and it works so well out of the box.

Thought on this anyone?

**Comment by tombruijn** [comment]
I'm of the same opinion. I mean, I started using Backup with Dropbox as well, but more as a hobby thing. I would not recommend it for storing business backups.

I'm using AWS S3 as well for backups. My hobby projects, the only thing I still use the Backup gem for, are about $1 per month. I've spent a lot more on backups. Good backups, stored on multiple locations, will cost some amount of money to store. Plus, free services aren't actually free.

Dropbox is a good entry-type of backup store for new users, but I wouldn't recommend using it for long. If no one considers Dropbox to be real good storage solution for backups, I'm okay with dropping it.
I'm much happier to see @nynhex have a good work-life balance than to support Dropbox APIv2 anytime soon.

**Comment by stuartellis** [comment]
I ought to add that I am really impressed with Dropbox as a sync solution: I just don't think that it is the best option where you might want to keep versions around for a long time (or forever).

Also, not supporting Dropbox in the "official" repository would really just mean that we don't feel that we can maintain or support code for it ourselves. I'm writing a PR for the documentation to note that Dropbox does not currently work, and would not be opposed to adding a link to another fork with Dropbox support.

**Comment by stuartellis** [comment]
Just to confirm that I have updated the documentation, with pull request #902.

**Comment by br4in3x** [comment]
@vtm9 Thank you, it works good! =)

**Comment by ulitiy** [comment]
@vtm9 
```
Bundler could not find compatible versions for gem "dropbox_api":
  In Gemfile:
    dropbox_api

    backup was resolved to 5.0.0.beta.2, which depends on
      dropbox_api (= 0.1.10)

Could not find gem 'dropbox_api (= 0.1.10)', which is required by gem 'backup', in any of the relevant sources:
  git://github.com/vtm9/dropbox_api.git (at chunked_file_uploader@541bb9d)
```

It seems you have a 0.1.9 version in this branch.

**Comment by vtm9** [comment]
@ulitiy, it's work for me:
```ruby
gem "backup", git: "https://github.com/vtm9/backup.git", branch: "dropbox_api_v2"
```

**Comment by vtm9** [comment]
https://github.com/Jesus/dropbox_api/pull/34

My PR for dropbox_api with chunked uploader was merged. 
So, it's simple to change V1 to V2 dropbox adapters. 
Now my fork works good, but if upgrade current gem it's will be better to create new PR with new version of dropbox_api gem.

**Comment by axelaxel** [comment]
I use your fork, too. Thanks a lot Vitaly!

**Comment by hedgesky** [comment]
Quick note for future visitors. If you're receiving errors like this:

```
[2017/12/12 21:12:48][error] Config::Error: Invalid Configuration File
[2017/12/12 21:12:48][error]   The configuration file at '/home/deployer/Backup/config.rb'
[2017/12/12 21:12:48][error]   does not appear to be a Backup v5.x configuration file.
[2017/12/12 21:12:48][error]   If you have upgraded to v5.x from a previous version,
[2017/12/12 21:12:48][error]   you need to upgrade your configuration file.
[2017/12/12 21:12:48][error]   Please see the instructions for upgrading in the Backup documentation.
```

then you might want to replace line `# Backup v4.x Configuration` with `# Backup v5.x Configuration` at the very top of your `config.rb`.

**Comment by hiphapis** [comment]
I'm so sad. why did not support Dropbox?
