### ISSUE TITLE
SyntaxError when model name contains an integer

### ISSUE THREAD

**Issue by neidiom** [backup/backup#913]
When model name container a integer backup check fails

````
 backup generate:model --trigger 24backup   --archives --storages='local' --compressor='gzip' --notifiers='mail' --databases='mysql' --no-splitter
````

````
backup check
````

````
[2017/12/19 15:32:09][error] CLI::Error
[2017/12/19 15:32:09][error] --- Wrapped Exception ---
[2017/12/19 15:32:09][error] SyntaxError: /root/Backup/models/24backup.rb:12: syntax error, unexpected tINTEGER, expecting tSTRING_CONTENT or tSTRING_DBEG or tSTRING_DVAR or tSTRING_END
[2017/12/19 15:32:09][error] Model.new(:24backup, 'Description for 24bac
[2017/12/19 15:32:09][error]              ^
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/gems/backup-5.0.0.beta.2/lib/backup/config.rb:47:in `instance_eval'
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/gems/backup-5.0.0.beta.2/lib/backup/config.rb:47:in `block in load'
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/gems/backup-5.0.0.beta.2/lib/backup/config.rb:46:in `each'
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/gems/backup-5.0.0.beta.2/lib/backup/config.rb:46:in `load'
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/gems/backup-5.0.0.beta.2/lib/backup/cli.rb:221:in `check'
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/gems/backup-5.0.0.beta.2/bin/backup:5:in `<top (required)>'
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/bin/backup:23:in `load'
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/bin/backup:23:in `<main>'
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `eval'
[2017/12/19 15:32:09][error] /usr/local/rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `<main>'
[2017/12/19 15:32:09][error] Configuration Check Failed.

````

**Comment by tombruijn** [comment]
Hi @neidiom,

That's correct. You should get that error. Ruby, the language in which the Backup gem is written, does not support class names starting with an integer. It's not something we can currently support without changing the way models work in a major way.

Please use a model that doesn't start with an integer.

24Backup won't work.
Backup24 does work.
